App/website/models.py
# this file contains the models for the database
from website import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Picture(db.Model):  # type: ignore
    # each picture can have a name, a description, date, and corresponding user
    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class User(db.Model, UserMixin):  # type: ignore
    # each user can have a name, email, password, and corresponding picture list
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(20), unique=True)
    password = db.Column(db.String(20))
    first_name = db.Column(db.String(20))
    # one user can have many pictures
    pictures = db.relationship('Picture')

App/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy  #1.3.18
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

# Create the app
def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'group1key'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Picture
    
    # Create the database
    create_database(app)

    # Create the login manager
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'  # type: ignore
    login_manager.init_app(app)

    # Create the user loader
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    # if the database doesn't exist, create it
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('created Database.')

App/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')  # type: ignore
        password = request.form.get('password')  # type: ignore
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Login success.', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password. Try again.', category='error')
        else:
            flash('Account not found.', category='error')

    return render_template("login.jinja", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        # Get the form data
        email = request.form.get('email')  # type: ignore
        first_name = request.form.get('firstName')  # type: ignore
        password1 = request.form.get('password1')  # type: ignore
        password2 = request.form.get('password2')  # type: ignore

        # Check if email already exists, flash error if it does
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Acccount already exists.', category='error')
        # if length of email is less than 7, flash error
        elif len(email) < 7:
            flash('Email must be greater than 7 characters.', category='error')
        # if length of first name is less than 2, flash error
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        # Check if passwords match, flash error if they don't
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        # Check if password is less than 7 characters, flash error if it is
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        # If all checks pass, add user to database
        else:
            # Create new user and hash password
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='sha256'))
            # Add user to database
            db.session.add(new_user)
            db.session.commit()
            # Log user in with flask login function
            login_user(new_user, remember=True)
            flash('Account created.', category='success')
            # Redirect to home page
            return redirect(url_for('views.home'))

    return render_template("sign_up.jinja", user=current_user)

App/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user

# import nasapy
# import os
from datetime import datetime
# import urllib.request
# from gtts import gTTS
import requests, json
import os
import openai
import copy
views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    # stores APi key and Api URL
    nasakey = "l1YsgpdqqiBEXpx1IqHfEp1DkqgysDrBvzjIeKVR"
    url = 'https://api.nasa.gov/planetary/apod?'
    
    if request.method == 'POST':
        date_changed = request.form.get('dateInput')    # type: ignore
        # if there is user input, get the date and enter into parameters
        if date_changed:
            date_changed = datetime.strptime(date_changed, '%m/%d/%Y').date()
        params={
            'api_key': nasakey,
            'hd': 'True',
            'date': date_changed
         } 
    else:
        params={
            'api_key': nasakey,
            'hd': 'True',
            'date': datetime.today().strftime('%Y-%m-%d')
    }

    response = requests.get(url, params=params)
    # data has copyright, date, explaination, hdurl, media_type, service_version, title, url
    data = response.json()
    print(data)
    
    return render_template("home.jinja", user=current_user, data=data)

@views.route('/game', methods=['GET', 'POST'])
@login_required
def game():
    nasakey = "l1YsgpdqqiBEXpx1IqHfEp1DkqgysDrBvzjIeKVR"
    url = 'https://api.nasa.gov/planetary/apod?'
    
    if request.method == 'POST':
        date_changer = request.form.get('dateInputter')    # type: ignore
        # if there is user input, get the date and enter into parameters
        if date_changer:
            date_changer = datetime.strptime(date_changer, '%m/%d/%Y').date()
        params={
            'api_key': nasakey,
            'hd': 'True',
            'date': date_changer
         } 
    else:
        params={
            'api_key': nasakey,
            'hd': 'True',
            'date': datetime.today().strftime('%Y-%m-%d')
    }
    response = requests.get(url, params=params)
    # data has copyright, date, explaination, hdurl, media_type, service_version, title, url
    data = response.json()
    url_ai = 'https://api.openai.com/v1/images/generations'
    user_prompt = request.form.get('UserDescription')  # type: ignore
    if request.method == 'POST':
        if user_prompt:
            OPENAI_API_KEY = ''

            headers = {
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {OPENAI_API_KEY}',
            }

            json_data = {
                'prompt': user_prompt,
                'n': 3,
                'size': '256x256',
            }
            response2 = requests.post('https://api.openai.com/v1/images/generations', headers=headers, json=json_data)
            data2 = response2.json()
            print(data2)
            return render_template("game.jinja", user=current_user, data=data, data2=data2)
    return render_template("game.jinja", user=current_user, data=data)

App/website/templates/base.jinja
<!-- this file contains the code for the main window of the application -->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- bootstrap stylesheets -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <span class="navbar-brand mb-0 h1">Star Guessing</span>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <!-- if user is logged in, display home and logout on taskbar-->
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <li class="nav-item">
            <a class="nav-link tm-nav-link" href="{{url_for('views.game')}}">Game</a>
          </li>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          <!-- if user is not logged in, display login and register on taskbar-->
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          <a class="nav-item nav-link" id="googleLogin" href="/google-login">Google LogIn</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} 
      {% if messages %} 
      <!-- flash/display messages -->
        {% for category, message in messages %} 
          <!-- message is error, display error message -->
          {% if category == 'error' %}
          <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <!-- if message is success, display success message -->
          {% else %}
          <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %} 
        {% endfor %} 
      {% endif %} 
    {% endwith %}

    <!-- contains bootstrap packages for login, etc -->
    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

App/website/templates/game.jinja
<!-- this file contains the code for the "game" page -->

{% extends "base.jinja" %} 
{% block title %}Game{% endblock %} 

{% block content %}
<!--  	
npm install jquery
npm install bootstrap
npm install lessc
-->

<!-- datepicker -->
{% block scripts %}
<script>
    $('.input-group.date').datepicker({
        format: "mm/dd/yyyy",
        todayBtn: "linked",
        clearBtn: true,
        autoclose: true,
        todayHighlight: true
    });
</script>
{% endblock %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
</head>

<h1 align="center" > Test Your AI Image Generating Skills! </h1>

  <body style="background-color: ivory;">
  <br>
    
    <div class="input-group date" data-provide="datepicker" data-date-end-date="0d" data-date-start-date="01/01/2000">
      <div class="text-center">
        <form method="post" action = "/game">
          <label for= "date"> </label>
          <b>Change Image </b> 
          <input type="text" name="dateInputter" class="form-control" placeholder="Select Date">
          <div class="col-auto">
          
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        </form>
      </div>  
    </div>

        <!-- might not work -->
        <div class="input-group-addon">
            <span class="glyphicon glyphicon-th"></span>
        </div>
    </div>


    <!-- image display -->
    <br>
    <div class="text-center">
      {% if data_change %}
        <img src= {{data_change.hdurl}} class="rounded" style="height: 500px;" alt="Responsive image"/>
      {% else %}
        <img src= {{data.hdurl}} class="rounded" style="height: 500px;" alt="Responsive image"/>
      {% endif %}
    </div>
    <center>
    <form method="post" action = "/game">
      <center>
        <br>
        <label for="Name"><b>Describe the above image as best as you can.</b></label>
      </center>
      <br>
      
        <div class="col-md-10 my-1">
        {# center the form below #}
        
         
          <input type="text" name="UserDescription" class= "form-control" placeholder="Describe the Image">
          
        
        </div>
        <div class="col-auto">
          <button type="submit" class="btn btn-primary">Generate</button>
        </div>
      </div>
      
    </form>
    <br>   
    {%if data2%} 
      <img src= {{data2['data'][0]['url']}} style="height: 400px; width: 400px" class="img-fluid" alt="..."/> 
      <img src= {{data2['data'][1]['url']}} style="height: 400px; width: 400px" class="img-fluid" alt="..."/>
      <img src= {{data2['data'][2]['url']}} style="height: 400px; width: 400px" class="img-fluid" alt="..."/>
    {% endif %}  

  </body>

{% endblock %}
  

App/website/templates/home.jinja
<!-- this file contains the code for the "home" page (this is where picture diplay should be -->

{% extends "base.jinja" %} 
{% block title %}Home{% endblock %} 

{% block content %}
<!--  	
npm install jquery
npm install bootstrap
npm install lessc
-->

<!-- datepicker -->
{% block scripts %}
<script>
    $('.input-group.date').datepicker({
        format: "mm/dd/yyyy",
        todayBtn: "linked",
        clearBtn: true,
        autoclose: true,
        todayHighlight: true
    });
</script>
{% endblock %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
</head>

<h1 align="center"> Astronomy Picture of the Day </h1>
<br>
  <body style="background-color: ivory;">
    <div class="input-group date" data-provide="datepicker" data-date-end-date="0d" data-date-start-date="01/01/2000">
        <form method="post" action = "/">
          <div class="form-row align-items-center">
            <div class="col-auto">
              <input type="text" name="dateInput" class="form-control" placeholder="Select Date">
            </div>
            <div class="col-auto">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
        <!-- might not work -->
        <div class="input-group-addon">
            <span class="glyphicon glyphicon-th"></span>
        </div>
    </div>
  
    <!-- image display -->
    <br>
    <div class="text-center">
      <img src= {{data.hdurl}} class="rounded" style="height: 500px;" alt="Responsive image"/> 
    </div>
    <br>
    <b>Photographer </b> 
    <p>{{data.copyright}}</p>
    <b>Description </b> 
    <p>{{data.explanation}}</p>  
  </body>
{% endblock %}

App/website/templates/login.jinja
<!-- this file contains the code for the "login" page -->

{% extends "base.jinja" %} 
{% block title %}Login{% endblock %} 
{% block content %}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <!-- this is the email input -->
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <!-- this is the password input -->
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <!-- this is the login button -->
  <button type="login" class="btn btn-primary">Login</button>
</form>
{% endblock %}

App/website/templates/sign_up.jinja
<!-- this file contains the code for the "sign up" page -->

{% extends "base.jinja" %} 
{% block title %}Sign Up{% endblock %} 
{% block content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
   <!-- email input -->
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <!-- first name input -->
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <!-- password input -->
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <!-- password confirmation input -->
    <label for="password2">Password (Confirmation)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="sign_up" class="btn btn-primary">Sign Up</button>
</form>
{% endblock %}